[platformio]
default_envs = esp_hi_3c

[env:esp_hi_3c]
platform = espressif32@6.8.1
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=3
lib_deps =
  adafruit/Adafruit GFX Library@1.11.11
  adafruit/Adafruit ST7735 and ST7789 Library@1.10.4
  adafruit/Adafruit NeoPixel@1.12.3
  madhephaestus/ESP32Servo@3.0.6

